baseURL = "https://hugo-starter-site.netlify.app"
languageCode = "en-us"
title = "Hugo Starter Site"
copyright = "No copyright."

rssLimit = 20
staticDir = "static"
canonifyURLs = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  
[author]
	name = "Judah"
	email = "judah@joodaloop.com"

[params]
  description = "A better starting point for building Hugo sites."

[markup.goldmark.renderer]
    unsafe = "true"
